version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "Installing Node Modules"
      - node/with-cache:
          steps:
            - run: npm install
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "Running Build"
      - node/with-cache:
          steps:
            - run: npm run build && pwd

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            pwd
            tar -czf build.tar.gz dist/
            scp build.tar.gz netlify@34.93.26.100:/home/netlify/releases/
            ssh netlify@34.93.26.100 "cd /home/netlify/releases/; tar xf build.tar.gz; cp -rf /opt/care_fe/dist /opt/care_fe/dist.old; mv dist /opt/care_fe/dist"
workflows:
  care:
    jobs:
      - install
      - build :
          requires:
            - install
      - deploy:
          requires:
            - build