steps:
  - name: ZAP Scan
    uses: zaproxy/action-baseline@v0.3.0
    with:
      target: 'https://care.coronasafe.in'
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://care.coronasafe.in'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'