language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - libgdal-dev
      - libsqlite3-mod-spatialite
install:
  - pip install -q -r requirements/local.txt
script:
  - python manage.py makemigrations --check || exit 1
  - python manage.py test --settings=config.settings.test -n
