language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - libgdal-dev
      - libsqlite3-mod-spatialite
install:
  - pip install -q -r requirements.txt
script: pytest -v care/facility/tests/test_facility.py care/facility/tests/test_patient.py care/users/tests/test_users.py
