FROM egovio/care-production-base:v1.0
ARG WORK_DIR

COPY ${WORK_DIR}/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY ${WORK_DIR} /app

WORKDIR /app

EXPOSE 9000
CMD ["/bin/bash", "-c", "--","/app/celery_beat.sh"]